### ISSUE TITLE
Depth with another context

### ISSUE THREAD

**Issue by black-meridian** [Jako/SuperBoxSelect#24]
Hi, 

i have a problem to list more than 1 level if I use a parent from another context.

only the first level of resources is available.

thanks !

**Comment by Jako** [comment]
Could you send a screenshot of the SuperBoxSelect template variable setting? Or could you post the serialized value in the input_properties column of modx_site_tmplvars of the SuperBoxSelect template variable?

**Comment by black-meridian** [comment]
thanks ! here 2 screenshots from the same template, from two different context

the first TV show all resources (because, the parent is from the same context)

![Capture d’écran 2020-08-28 à 10 55 20](https://user-images.githubusercontent.com/36260542/91541857-40e08200-e91d-11ea-8b92-b913dbd61e4c.png)

the second one, from another context, show only the first level 👍 

![Capture d’écran 2020-08-28 à 10 55 24](https://user-images.githubusercontent.com/36260542/91541942-5ce42380-e91d-11ea-9e3a-1ead685b7c58.png)

**Comment by black-meridian** [comment]
and here a screen from the TV config : 

![Capture d’écran 2020-08-28 à 11 08 58](https://user-images.githubusercontent.com/36260542/91543769-04158a80-e91f-11ea-8786-cd45e3152b6b.png)

**Comment by Jako** [comment]
It's a bug caused by this line: https://github.com/Jako/SuperBoxSelect/blob/master/core/components/superboxselect/processors/types/resources/getlist.class.php#L96

I am quite busy at the moment and the bug looks quite nasty and I can't fix this directly.

**Comment by black-meridian** [comment]
Thanks Jaco for your answer 

my developer did a little hack before line 96 : 

```
$myParent=$this->modx->getObject('modResource',$parent);
if($myParent){
	$contextKey=$myParent->get('context_key');
} 
```

it seems to work

**Comment by Jako** [comment]
It should be fixed like this.

**Comment by Jako** [comment]
Could you check this patch, please. Then I don't have to create that configuration on my test installation.

**Comment by black-meridian** [comment]
Hi Jako, sorry for the delay. Your patch doesn't fix the search

**Comment by Jako** [comment]
For whatever reason, `$modx->resourceMap` is empty during retrieving the child IDs with `$modx->getChildIds`. Maybe because no (web?) context is initialized at that moment. After retrieving the parent resource, this is the case (at least) for the context of the retrieved resource. So the fix of your developer is (almost right). I have wrapped it with a check.
